// <auto-generated />
using System;
using Exam_SK.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamSK.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Exam_SK.Models.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<int?>("MessagesId");

                    b.Property<string>("Name");

                    b.Property<string>("UsersUName");

                    b.HasKey("Id");

                    b.HasIndex("MessagesId");

                    b.HasIndex("UsersUName");

                    b.ToTable("ChatRoom");
                });

            modelBuilder.Entity("Exam_SK.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateSent");

                    b.Property<bool>("IsRead");

                    b.Property<string>("Messages")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Exam_SK.Models.User", b =>
                {
                    b.Property<string>("UName")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("UName");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Exam_SK.Models.ChatRoom", b =>
                {
                    b.HasOne("Exam_SK.Models.Message", "Messages")
                        .WithMany("chatRooms")
                        .HasForeignKey("MessagesId");

                    b.HasOne("Exam_SK.Models.User", "Users")
                        .WithMany("chatRooms")
                        .HasForeignKey("UsersUName");
                });
#pragma warning restore 612, 618
        }
    }
}
